server: 
  port: 9003
spring: 
  application:  
    name: tensquare-qa #问答
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.48.128:3306/tensquare_qa?characterEncoding=UTF8 #避免乱码
    username: root
    password: 123456
  jpa: 
    database: MySQL
    show-sql: true
